name: Hostloc

on:
  schedule:
    - cron: '06 23 * * *'
    # - cron: '36 1-16/2 * * *'
  watch:
     types: started

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r hostloc/requirements.txt
    - name: Run hostloc checkin
      env:
        hostloc_username: ${{ secrets.hostloc_username }}
        hostloc_password: ${{ secrets.hostloc_password }}
        hostloc_onebyone: false
      run: |
        python hostloc/hostloc.py
        
        
